(()=>{"use strict";const URL="https://jbxeaqitujkmzulbpjmy.supabase.co",KEY="sb_publishable_zUAeB4TcRF8nWUwTzQcm1w_W7H";let session=null,rows=[];const $=id=>document.getElementById(id),status=x=>$("status").textContent=x;
async function auth(path,body){const r=await fetch(URL+"/auth/v1/"+path,{method:"POST",headers:{apikey:KEY,"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||"Authentication failed");return j}
$("signin").onclick=async()=>{try{session=await auth("token?grant_type=password",{email:$("email").value,password:$("password").value});$("login").hidden=true;$("app").hidden=false;await loadTables()}catch(e){status(e.message)}};
$("claim").onclick=async()=>{try{const r=await fetch("/api/admin-config?action=bootstrap",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({token:$("bootstrap").value})});const j=await r.json();status(j.ok?"Administrator activated. Sign in again.":j.error)}catch(e){status(e.message)}};
async function loadTables(){const r=await fetch("/api/admin-config?action=tables",{headers:{Authorization:"Bearer "+session.access_token}});const j=await r.json();$("table").innerHTML=j.tables.map(x=>'<option>'+x+'</option>').join("");await load()}
$("table").onchange=load;$("refresh").onclick=load;
async function load(){const t=$("table").value;if(!t)return;const r=await fetch("/api/admin-config?table="+encodeURIComponent(t),{headers:{Authorization:"Bearer "+session.access_token}});const j=await r.json();rows=j.rows||[];render()}
function render(){const e=$("editor");e.innerHTML=rows.map((row,i)=>'<article class="card admin-row"><textarea id="r'+i+'" rows="12"></textarea><button data-i="'+i+'" class="save">Save</button><button data-i="'+i+'" class="del">Delete</button></article>').join("");rows.forEach((r,i)=>$("r"+i).value=JSON.stringify(r,null,2));e.querySelectorAll(".save").forEach(b=>b.onclick=()=>save(+b.dataset.i));e.querySelectorAll(".del").forEach(b=>b.onclick=()=>del(+b.dataset.i))}
async function save(i){try{const row=JSON.parse($("r"+i).value),t=$("table").value;const keys={industry_profiles:["id"],country_market_profiles:["country_code"],industry_country_scenarios:["id"],journey_templates:["id"],option_catalog:["catalog_key","option_value"],ui_config:["config_key"],demo_scenarios:["id"]}[t];const exists=rows[i]&&keys.every(k=>rows[i][k]!==undefined);const r=await fetch("/api/admin-config?table="+encodeURIComponent(t),{method:exists?"PATCH":"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify(row)});const j=await r.json();if(!r.ok)throw Error(j.error);await load()}catch(e){alert(e.message)}}
async function del(i){if(!confirm("Delete this configuration record?"))return;const t=$("table").value,keys={industry_profiles:["id"],country_market_profiles:["country_code"],industry_country_scenarios:["id"],journey_templates:["id"],option_catalog:["catalog_key","option_value"],ui_config:["config_key"],demo_scenarios:["id"]}[t],row=rows[i],q=Object.fromEntries(keys.map(k=>[k,row[k]]));const r=await fetch("/api/admin-config?table="+encodeURIComponent(t),{method:"DELETE",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify(q)});if(r.ok)load();else alert((await r.json()).error)}
$("new").onclick=()=>{rows=[{} ,...rows];render()}})();