(function () {
"use strict";

window.AutomationScanIntelligence = {
  version: "2.0.0",
  methodology: ["Discover","Baseline","Map","Assess","Compare","Validate","Quantify","Decide","Plan"],
  industries: {
    "Retail": {models:["Department / specialty retail","Grocery / convenience","Fashion / apparel","Wholesale + retail","Omnichannel / marketplace","Direct-to-consumer","Franchise"],processes:["Merchandising","Buying and procurement","Pricing and promotions","Demand planning","Replenishment","POS and store operations","E-commerce","Order fulfilment","Returns","Customer loyalty","Finance"],pains:["Poor inventory visibility","Slow merchandising decisions","Spreadsheet-driven planning","High integration effort","Customer data fragmentation","Margin pressure"],regulatory:["Consumer privacy","PCI DSS where payment-card data is handled","Country-specific consumer and tax requirements"]},
    "Manufacturing": {models:["Discrete manufacturing","Process manufacturing","Engineer-to-order","Make-to-stock","Make-to-order","Contract manufacturing"],processes:["Product lifecycle","Bill of materials","Planning and scheduling","Procurement","Production","Quality","Warehouse","Maintenance","Costing","Finance"],pains:["Planning volatility","Manual production processes","Inventory imbalance","Quality issues","Legacy customisation","High operational cost"],regulatory:["Product and workplace requirements vary by jurisdiction","Traceability and quality controls where applicable"]},
    "Distribution": {models:["Wholesale distribution","B2B distribution","Consumer distribution","Import / export","3PL / logistics"],processes:["Procurement","Demand planning","Inventory","Warehouse","Order management","Pricing","Transportation","Returns","Customer management","Finance"],pains:["Inventory imbalance","Slow order fulfilment","Manual pricing","Warehouse inefficiency","Integration complexity","Margin leakage"],regulatory:["Trade, tax, customs and product requirements vary by geography"]},
    "Healthcare": {models:["Provider","Hospital","Clinic network","Healthcare services","Medical distribution"],processes:["Patient / member administration","Scheduling","Supply chain","Procurement","Billing","Finance","Compliance","Workforce","Reporting","Data management"],pains:["Manual administration","Fragmented data","Compliance burden","Scheduling inefficiency","Supply chain cost","Reporting delays"],regulatory:["HIPAA/HITECH where applicable","Local health-data and retention requirements"]},
    "Professional Services": {models:["Consulting","IT services","Engineering services","Managed services","Project-based services","Subscription services"],processes:["Opportunity management","Project delivery","Resource planning","Time and expenses","Billing","Revenue recognition","Procurement","Finance","Customer management"],pains:["Poor resource utilisation","Manual project administration","Billing leakage","Forecasting difficulty","Disconnected systems","Margin pressure"],regulatory:["Contract, tax, privacy and professional obligations vary by jurisdiction"]},
    "Hospitality": {models:["Hotel","Resort","Restaurant group","Travel / leisure","Multi-property hospitality"],processes:["Reservations","Property operations","Procurement","Inventory","Point of sale","Housekeeping","Revenue management","Guest experience","Finance"],pains:["Fragmented property systems","Manual operations","Revenue leakage","Poor guest data","Procurement inefficiency","Reporting delays"],regulatory:["Payment, privacy, tax and local hospitality requirements"]},
    "Construction": {models:["General contractor","Specialty contractor","Design-build","Engineering & construction","Infrastructure"],processes:["Estimating","Bid management","Project planning","Procurement","Subcontract management","Cost control","Change orders","Field operations","Billing","Finance"],pains:["Cost overruns","Manual field reporting","Subcontractor coordination","Change-order leakage","Document fragmentation","Cash-flow pressure"],regulatory:["Construction, safety, tax, labour and public procurement requirements vary by jurisdiction"]},
    "Engineering": {models:["Engineering services","Project engineering","EPC","Product engineering","Professional services"],processes:["Opportunity management","Project planning","Engineering change","Resource planning","Procurement","Project accounting","Quality","Document control","Billing"],pains:["Resource bottlenecks","Engineering change complexity","Document control","Project margin leakage","Disconnected systems"],regulatory:["Industry-specific engineering, safety and contractual requirements"]},
    "Telecommunications": {models:["Network operator","Service provider","Managed services","Wholesale telecom"],processes:["Customer acquisition","Subscription billing","Order management","Network operations","Asset management","Field service","Procurement","Revenue assurance","Finance"],pains:["Legacy integrations","Revenue leakage","High service complexity","Asset visibility","Billing exceptions"],regulatory:["Telecom licensing, privacy, data retention and local regulatory requirements"]},
    "Utilities": {models:["Electric utility","Gas utility","Water utility","Multi-utility"],processes:["Asset management","Work management","Metering","Customer service","Billing","Field service","Procurement","Capital projects","Finance"],pains:["Asset ageing","Field-work inefficiency","Billing complexity","Regulatory reporting","Legacy systems","Outage response"],regulatory:["Utility regulation, metering, environmental and critical-infrastructure requirements vary by jurisdiction"]},
    "Public Sector": {models:["Central government","Local government","Public agency","Government-owned enterprise"],processes:["Budgeting","Fund accounting","Procurement","Grants","Citizen services","Workforce","Asset management","Reporting","Compliance"],pains:["Legacy systems","Procurement constraints","Reporting burden","Manual approvals","Data silos"],regulatory:["Public procurement, records, security, accessibility and jurisdiction-specific requirements"]},
    "Financial Services": {models:["Banking","Payments","Lending","Wealth management","Fintech"],processes:["Customer onboarding","Finance","Payments","Risk","Compliance","Procurement","Case management","Reporting","Data management"],pains:["Regulatory burden","Legacy platforms","Manual controls","Data fragmentation","Slow reporting"],regulatory:["SOX where applicable","PCI DSS where applicable","KYC/AML and jurisdiction-specific financial regulation"]},
    "Life Sciences": {models:["Pharmaceutical","Biotechnology","Medical devices","Clinical services"],processes:["R&D","Quality","Batch / lot management","Supply chain","Manufacturing","Validation","Regulatory reporting","Finance"],pains:["Validation effort","Traceability","Quality records","Supply-chain complexity","Data integrity"],regulatory:["GxP where applicable","FDA 21 CFR Part 11 where applicable","Local product and health regulations"]},
    "Consumer Products": {models:["Branded products","CPG","Wholesale consumer products","Direct-to-consumer"],processes:["Product lifecycle","Demand planning","Procurement","Manufacturing","Trade promotion","Inventory","Distribution","Customer management","Finance"],pains:["Forecast volatility","Margin pressure","Trade complexity","Inventory imbalance","Data fragmentation"],regulatory:["Product labelling, consumer, tax and privacy requirements vary by market"]},
    "Automotive": {models:["OEM","Tier supplier","Aftermarket","Dealer network"],processes:["Product lifecycle","Demand planning","Procurement","Production","Quality","Supplier management","Logistics","Warranty","Finance"],pains:["Supplier complexity","Production volatility","Traceability","Quality","EDI/integration burden"],regulatory:["Automotive quality, safety, traceability and regional requirements vary"]},
    "High Tech": {models:["Hardware","Software","SaaS","Semiconductor","Contract manufacturing"],processes:["Product lifecycle","Subscription management","Order management","Procurement","Planning","Manufacturing","Support","Revenue recognition","Finance"],pains:["Rapid product change","Revenue complexity","Supply volatility","Legacy applications","Integration burden"],regulatory:["Export controls, privacy, security and product requirements vary"]},
    "Aerospace & Defense": {models:["OEM","Tier supplier","MRO","Defense contractor","Government program"],processes:["Program management","Engineering change","Configuration management","Quality","Supply chain","MRO","Contract accounting","Project control","Compliance"],pains:["Configuration complexity","Long program cycles","Traceability","Contract cost control","Supplier risk"],regulatory:["ITAR/CMMC and contract-specific requirements may apply; validate jurisdiction and program scope"]},
    "Agriculture & Agribusiness": {models:["Grower","Cooperative","Agricultural distribution","Food processing","Commodity trading"],processes:["Planning","Procurement","Production","Land / crop management","Inventory","Commodity management","Logistics","Quality","Finance"],pains:["Seasonality","Commodity volatility","Traceability","Equipment visibility","Manual field data"],regulatory:["Food, environmental, land, tax and traceability requirements vary"]},
    "Energy & Utilities": {models:["Energy producer","Oil & gas","Renewables","Energy services","Utility"],processes:["Asset management","Field operations","Maintenance","Procurement","Project management","Metering","Trading","Compliance","Finance"],pains:["Asset intensity","Field-service complexity","Regulatory reporting","Maintenance cost","Legacy integration"],regulatory:["Environmental, safety, energy-market and critical-infrastructure requirements vary"]},
    "Food & Beverage": {models:["Food manufacturing","Beverage manufacturing","Restaurant group","Food distribution","D2C food"],processes:["Recipe / formulation","Procurement","Batch production","Quality","Lot traceability","Shelf-life","Warehouse","Distribution","Finance"],pains:["Shelf-life risk","Traceability","Quality holds","Forecast volatility","Waste","Manual batch records"],regulatory:["FSMA/FDA requirements may apply in the US; local food-safety rules vary"]},
    "Chemicals": {models:["Specialty chemicals","Commodity chemicals","Batch processing","Distribution"],processes:["Formula management","Batch production","Quality","Hazard management","Procurement","Inventory","Traceability","Logistics","Finance"],pains:["Batch genealogy","Hazmat compliance","Formula control","Quality","Inventory risk"],regulatory:["Hazardous-material, environmental, product and transport requirements vary by jurisdiction"]},
    "Media & Entertainment": {models:["Subscription media","Broadcast","Publishing","Production studio","Digital content"],processes:["Content lifecycle","Rights management","Subscription billing","Advertising","Production","Royalty management","Customer management","Finance"],pains:["Rights complexity","Subscription leakage","Content workflows","Fragmented data","Manual reporting"],regulatory:["Privacy, copyright, content and local media requirements vary"]},
    "Nonprofit": {models:["Charity","Foundation","Association","Membership organization"],processes:["Fund accounting","Grant management","Donor management","Procurement","Programs","Budgeting","Reporting","Finance"],pains:["Restricted-fund complexity","Manual grant reporting","Donor data fragmentation","Budget visibility"],regulatory:["Charitable reporting, restricted-fund and local nonprofit rules vary"]},
    "Real Estate & Property Management": {models:["Property owner","Property manager","Developer","REIT","Commercial real estate"],processes:["Lease management","Property operations","Tenant management","Work orders","Capital projects","Procurement","Rent billing","Finance"],pains:["Lease complexity","Manual work orders","Tenant data fragmentation","Cash-flow visibility","Document volume"],regulatory:["Property, lease, tax, privacy and local reporting requirements vary"]},
    "Insurance": {models:["Property & casualty","Life insurance","Broker","Insurtech"],processes:["Policy administration","Underwriting","Claims","Billing","Customer service","Finance","Risk","Compliance","Reporting"],pains:["Legacy core systems","Claims handling","Manual underwriting","Regulatory reporting","Data fragmentation"],regulatory:["Insurance regulation, privacy, solvency and jurisdiction-specific requirements vary"]},
    "Other": {models:["B2B","B2C","Subscription","Project-based","Mixed / diversified"],processes:["Sales","Procurement","Operations","Inventory","Customer service","Finance","Reporting","People and workforce"],pains:["Manual work","Disconnected applications","Poor visibility","High operating cost","Legacy technology","Slow decision making"],regulatory:["Determine applicable jurisdiction and sector requirements before making a compliance conclusion"]}
  },
  candidates: {
    "Oracle": {type:"ERP + industry ecosystem", products:"Fusion Cloud ERP and industry applications", industries:["Retail","Manufacturing","Distribution","Healthcare","Financial Services","Hospitality","Public Sector","Utilities"], caps:["Finance","Procurement","Supply Chain","Order Management","Inventory","Planning","Analytics","Industry applications"], unique:"Broad enterprise suite plus industry applications and cloud platform; validate exact industry scope and release.", url:"https://www.oracle.com/erp/"},
    "SAP": {type:"ERP + industry ecosystem", products:"SAP Cloud ERP / S/4HANA and industry solutions", industries:["Retail","Manufacturing","Distribution","Life Sciences","Automotive","Consumer Products","Utilities","Public Sector"], caps:["Finance","Procurement","Supply Chain","Manufacturing","Planning","Warehouse","Analytics","Industry solutions"], unique:"Deep enterprise process and industry ecosystem; validate fit-to-standard, localization and implementation complexity.", url:"https://www.sap.com/products/erp.html"},
    "Microsoft Dynamics 365": {type:"ERP + business application ecosystem", products:"Dynamics 365 Finance, Supply Chain, Commerce and related applications", industries:["Retail","Distribution","Manufacturing","Professional Services","Construction","Healthcare","Public Sector"], caps:["Finance","Procurement","Supply Chain","Inventory","Commerce","Warehouse","Projects","CRM","Analytics"], unique:"ERP, CRM, commerce and Microsoft ecosystem integration; validate architecture and required modules.", url:"https://www.microsoft.com/dynamics-365"},
    "Infor CloudSuite": {type:"Industry ERP + cloud suite", products:"Infor CloudSuite", industries:["Retail","Manufacturing","Distribution","Healthcare","Hospitality","Aerospace & Defense","Food & Beverage"], caps:["Finance","Supply Chain","Manufacturing","Retail","Warehouse","Asset management","Industry workflows","Analytics"], unique:"Industry-oriented CloudSuite portfolio and potential continuity for existing Infor estates; validate target industry edition.", url:"https://www.infor.com/solutions"},
    "NetSuite": {type:"Cloud ERP", products:"Oracle NetSuite", industries:["Retail","Distribution","Professional Services","Manufacturing","Nonprofit","High Tech"], caps:["Financials","Procurement","Inventory","Order Management","Commerce","Projects","Planning","Analytics"], unique:"Cloud ERP oriented toward growing and mid-market organizations; validate scale, localization and advanced process requirements.", url:"https://www.netsuite.com/portal/products/erp.shtml"},
    "IFS Cloud": {type:"ERP + operational suite", products:"IFS Cloud", industries:["Manufacturing","Aerospace & Defense","Energy & Utilities","Construction","Engineering","Telecommunications","Service"], caps:["Finance","Supply Chain","Manufacturing","Asset Management","Service","Projects","Planning"], unique:"Strong operational, asset, service and project orientation; validate industry-specific functional depth.", url:"https://www.ifs.com/solutions"},
    "Epicor": {type:"Industry ERP", products:"Epicor Kinetic and industry applications", industries:["Manufacturing","Distribution","Food & Beverage","Chemicals"], caps:["Finance","Procurement","Inventory","Manufacturing","Supply Chain","Distribution"], unique:"Manufacturing/distribution-oriented ERP with industry capabilities; validate global footprint and complex-enterprise needs.", url:"https://www.epicor.com/"},
    "Sage X3": {type:"ERP", products:"Sage X3", industries:["Manufacturing","Distribution","Food & Beverage","Chemicals","Life Sciences"], caps:["Finance","Procurement","Inventory","Manufacturing","Supply Chain","Distribution","Quality"], unique:"Process-oriented ERP relevant to product-centric organizations; validate advanced planning, global and regulated requirements.", url:"https://www.sage.com/en-us/products/sage-x3/"},
    "Acumatica": {type:"Cloud ERP", products:"Acumatica Cloud ERP", industries:["Retail","Distribution","Manufacturing","Construction","Professional Services"], caps:["Financials","Distribution","Inventory","Order Management","Manufacturing","Commerce","Projects"], unique:"Cloud ERP with strong distribution, construction and mid-market patterns; validate enterprise-scale requirements.", url:"https://www.acumatica.com/"},
    "Unit4": {type:"ERP", products:"Unit4 ERP", industries:["Professional Services","Public Sector","Nonprofit","Education"], caps:["Finance","Procurement","Projects","Services","Planning","Analytics"], unique:"Service-centric ERP orientation for organizations where projects, people and financials are tightly linked.", url:"https://www.unit4.com/"},
    "Workday": {type:"Cloud business suite", products:"Workday Financial Management and related applications", industries:["Professional Services","Healthcare","Public Sector","Financial Services"], caps:["Finance","Procurement","Projects","Workforce","Planning","Analytics"], unique:"Strong finance/workforce platform orientation; validate operational ERP depth where manufacturing or complex supply chain is central.", url:"https://www.workday.com/"},
    "Odoo": {type:"Modular business suite", products:"Odoo", industries:["Retail","Distribution","Manufacturing","Professional Services","Nonprofit"], caps:["Finance","Sales","Inventory","Purchase","Manufacturing","POS","eCommerce"], unique:"Broad modular application footprint; validate governance, scale, localization and specialist requirements.", url:"https://www.odoo.com/"},
    "Manhattan Active": {type:"Specialist supply-chain platform", products:"Manhattan Active", industries:["Retail","Distribution","Manufacturing"], caps:["Warehouse","Order Management","Inventory","Transportation","Fulfilment"], unique:"Specialist supply-chain capabilities that can complement rather than replace an ERP core.", url:"https://www.manh.com/"},
    "Blue Yonder": {type:"Specialist supply-chain platform", products:"Blue Yonder", industries:["Retail","Manufacturing","Distribution","Consumer Products"], caps:["Planning","Demand","Supply","Warehouse","Order Management","Merchandising"], unique:"Planning, fulfillment and supply-chain specialization; evaluate as a complement or component of a composable architecture.", url:"https://blueyonder.com/"},
    "Sage Intacct": {type:"Cloud financial management", products:"Sage Intacct", industries:["Professional Services","Nonprofit","Healthcare"], caps:["Financials","Procurement","Projects","Reporting","Planning"], unique:"Finance-led cloud platform; evaluate when core operational manufacturing/supply-chain requirements sit elsewhere.", url:"https://www.sage.com/en-us/products/sage-intacct/"},
    "Deltek": {type:"Industry ERP / project platform", products:"Deltek", industries:["Professional Services","Aerospace & Defense","Engineering","Construction"], caps:["Projects","Finance","Resource planning","Contract management","Project accounting"], unique:"Project and contract-centric capabilities relevant to complex professional/project organizations.", url:"https://www.deltek.com/"},
    "Medius": {type:"Specialist finance automation", products:"Medius", industries:["Professional Services","Manufacturing","Distribution","Healthcare"], caps:["Accounts payable","Procurement","Invoice automation","Spend management"], unique:"Can complement an ERP by automating procure-to-pay and invoice workflows.", url:"https://www.medius.com/"},
    "Veeva": {type:"Industry application ecosystem", products:"Veeva", industries:["Life Sciences"], caps:["Quality","Regulatory","Clinical","Commercial","Content"], unique:"Life-sciences-specific application ecosystem; generally complements rather than replaces the ERP core.", url:"https://www.veeva.com/"},
    "Guidewire": {type:"Industry application platform", products:"Guidewire", industries:["Insurance"], caps:["Policy administration","Billing","Claims","Underwriting"], unique:"Insurance-core specialization; evaluate alongside finance/ERP rather than as a generic ERP replacement.", url:"https://www.guidewire.com/"},
    "Yardi": {type:"Property management platform", products:"Yardi", industries:["Real Estate & Property Management"], caps:["Property management","Lease administration","Tenant management","Accounting"], unique:"Property-centric operating platform; evaluate alongside corporate finance/ERP requirements.", url:"https://www.yardi.com/"},
    "ServiceNow": {type:"Workflow / service platform", products:"ServiceNow", industries:["Telecommunications","Healthcare","Public Sector","Financial Services","Utilities","Manufacturing"], caps:["Workflow","Case management","Service management","Asset workflows","Automation"], unique:"Workflow and service orchestration layer that can complement ERP and specialist systems.", url:"https://www.servicenow.com/"}
  },
  regulatoryDisclaimer: "Regulatory applicability depends on jurisdiction, legal entity, business activity and data/process scope. AutomationScan provides considerations, not legal advice; validate requirements with qualified legal/compliance professionals.",
  maturityLevels: [
    {level:1,name:"Fragmented",description:"Manual, disconnected processes with limited ownership or measurement."},
    {level:2,name:"Standardising",description:"Core processes are documented and repeatable, but systems and data remain siloed."},
    {level:3,name:"Integrated",description:"Core processes and applications are connected with defined controls and shared data."},
    {level:4,name:"Optimised",description:"Processes are measured, continuously improved and increasingly automated."},
    {level:5,name:"Intelligent / Adaptive",description:"Data, automation and AI support proactive decisions with governed human oversight."}
  ],
  tools: [
    {slug:"erp-shortlist",name:"ERP Vendor Shortlist Generator",description:"Build an investigation shortlist from industry, business model, current ERP and requirements."},
    {slug:"erp-health-check",name:"ERP Health Check",description:"Assess process, data, integration, adoption and customization health after go-live."},
    {slug:"erp-tco",name:"ERP TCO Calculator",description:"Model current and future-state technology costs using your own assumptions."},
    {slug:"migration-readiness",name:"ERP Migration Readiness",description:"Identify data, integration, process and change-readiness factors before migration."},
    {slug:"automation-opportunity",name:"Automation Opportunity Scanner",description:"Prioritize processes by effort, pain, repeatability and transformation value."},
    {slug:"application-rationalisation",name:"Application Portfolio Assessment",description:"Classify applications as keep, modernize, complement, consolidate or retire."},
    {slug:"compliance-check",name:"Compliance Considerations Checker",description:"Identify potentially relevant regulatory topics by industry and geography."},
    {slug:"business-case",name:"Transformation Business Case Builder",description:"Build a transparent scenario model from user-supplied costs and benefits."}
  ]
};
})();