const INDUSTRIES={
Retail:{models:["Department / specialty retail","Grocery / convenience","Fashion / apparel","Wholesale + retail","Omnichannel / marketplace"],processes:["Merchandising & assortment","Buying & supplier management","Pricing / promotions / markdowns","Demand forecasting & replenishment","Allocation & inventory","Store operations / POS","eCommerce / order management","Warehouse / fulfilment","Returns / reverse logistics","Customer / loyalty","Finance / P2P / O2C","Product / SKU / location master data","Retail analytics & planning"],pains:["Stockouts / overstocks","Margin leakage / markdown pressure","Spreadsheet-based planning","Poor inventory visibility","Disconnected POS / eCommerce","Slow assortment decisions","Manual supplier processes","Complex integrations","Store-to-warehouse imbalance"]},
Manufacturing:{models:["Discrete manufacturing","Process manufacturing","Engineer-to-order","Make-to-stock","Make-to-order"],processes:["Demand planning","S&OP","MRP / production planning","BOM / routing","Shop-floor execution","Quality management","Procurement","Supplier collaboration","Inventory / warehouse","Maintenance / assets","Order management","Costing / finance","Traceability / compliance","Product lifecycle"],pains:["Planning instability","Production downtime","Inventory excess","Manual scheduling","Quality / traceability gaps","Supplier risk","Cost variance","Disconnected shop floor","Legacy customisations"]},
Distribution:{models:["Wholesale distribution","3PL / logistics","Industrial distribution","Food distribution","Pharma distribution"],processes:["Demand planning","Purchasing","Inventory optimisation","Warehouse / WMS","Order management","Pricing / rebates","Transportation","Supplier management","Customer service","EDI / integration","Finance / P2P / O2C","Analytics"],pains:["Low inventory accuracy","Warehouse inefficiency","Margin leakage","Manual order entry","Poor demand visibility","Transport cost","Customer service delays","EDI complexity"]},
Healthcare:{models:["Hospital / health system","Clinic network","Diagnostics","Medical devices","Healthcare services"],processes:["Patient / provider operations","Scheduling","Supply chain","Procurement","Inventory","Finance","Compliance","Billing / revenue cycle","Asset / equipment management","Analytics / data","Integration / interoperability"],pains:["Manual administration","Supply shortages","Compliance burden","Fragmented data","Revenue leakage","Scheduling inefficiency","Integration complexity","Asset visibility"]},
"Professional Services":{models:["Consulting","IT services","Engineering services","Managed services","Legal / advisory"],processes:["Lead-to-project","Resource planning","Time & expense","Project delivery","Utilisation","Billing / revenue recognition","Contracts","Procurement","Finance","Knowledge / collaboration","CRM","Analytics"],pains:["Low billable utilisation","Manual timesheets","Revenue leakage","Poor resource forecasting","Project margin visibility","Fragmented CRM / ERP","Slow billing"]},
Hospitality:{models:["Hotel group","Restaurant group","Travel / leisure","Resort","Multi-brand hospitality"],processes:["Reservations","Property / venue operations","POS","Procurement","Inventory","Revenue management","Housekeeping / service","Customer loyalty","Workforce","Finance","Analytics","Digital commerce"],pains:["Demand volatility","Labour inefficiency","Food / stock waste","Disconnected POS","Poor guest data","Manual revenue management","Multi-property reporting"]},
Other:{models:["B2B","B2C","Platform / marketplace","Asset-intensive","Mixed"],processes:["Finance","Procurement","Sales / order management","Inventory / operations","Planning","Workforce","Customer service","Data / analytics","Integration","AI / automation"],pains:["Manual processes","Poor visibility","Legacy systems","Integration complexity","Data quality","High operating cost","Slow decision making"]}};
const platforms={Oracle:{caps:["Finance","Procurement","Supply chain","Warehouse","Merchandising","Planning","Inventory","Commerce","Data","AI","Integration"]},SAP:{caps:["Finance","Procurement","Supply chain","Warehouse","Planning","Inventory","Data","AI","Integration","Merchandising"]},Microsoft:{caps:["Finance","Procurement","Supply chain","Warehouse","Planning","Inventory","Commerce","CRM","Data","AI","Integration"]},Infor:{caps:["Finance","Procurement","Supply chain","Warehouse","Merchandising","Planning","Inventory","Data","AI","Integration"]},NetSuite:{caps:["Finance","Procurement","Inventory","Order management","Commerce","CRM","Data","Integration"]},IFS:{caps:["Finance","Procurement","Supply chain","Warehouse","Planning","Inventory","Asset / service","Data","AI","Integration"]}};
const form=document.getElementById("transformForm"),steps=[...document.querySelectorAll(".t-step")],next=document.getElementById("tNext"),back=document.getElementById("tBack"),generate=document.getElementById("tGenerate");let current=0;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function show(i){current=i;steps.forEach((s,n)=>s.classList.toggle("active",n===i));tProgress.textContent="Step "+(i+1)+" of "+steps.length;tProgressBar.style.width=((i+1)/steps.length*100)+"%";back.hidden=i===0;next.hidden=i===steps.length-1;generate.hidden=i!==steps.length-1;window.scrollTo({top:document.getElementById("navigator").offsetTop-30,behavior:"smooth"});}
function valid(){for(const f of steps[current].querySelectorAll("[required]"))if(!f.checkValidity()){f.reportValidity();return false}return true}
next.onclick=()=>{if(valid())show(Math.min(current+1,steps.length-1))};back.onclick=()=>show(Math.max(current-1,0));
function loadIndustry(){const d=INDUSTRIES[industry.value]||INDUSTRIES.Other;form.elements.businessModel.innerHTML='<option value="">Choose</option>'+d.models.map(x=>'<option>'+esc(x)+'</option>').join("");industryIntro.innerHTML="<b>"+esc(industry.value||"Your industry")+"</b> — "+d.processes.length+" core process areas will be considered, including: "+d.processes.slice(0,5).map(esc).join(" · ")+"…";industryProcesses.innerHTML=d.processes.map(x=>'<label><input type="checkbox" name="process" value="'+esc(x)+'">'+esc(x)+"</label>").join("");industryPains.innerHTML=d.pains.map(x=>'<label><input type="checkbox" name="pain" value="'+esc(x)+'">'+esc(x)+"</label>").join("");}
industry.onchange=loadIndustry;loadIndustry();
function read(){return{industry:industry.value,businessModel:form.elements.businessModel.value,current:form.elements.current.value,scale:form.elements.scale.value,processes:[...form.querySelectorAll('input[name="process"]:checked')].map(x=>x.value),customProcess:form.elements.customProcess.value,pains:[...form.querySelectorAll('input[name="pain"]:checked')].map(x=>x.value),painText:form.elements.painText.value,revenue:form.elements.revenue.value,employees:form.elements.employees.value,erpSpend:form.elements.erpSpend.value,custom:form.elements.custom.value,integration:form.elements.integration.value,migration:form.elements.migration.value,ecosystem:form.elements.ecosystem.value,horizon:form.elements.horizon.value,goals:[...form.querySelectorAll('input[name="goal"]:checked')].map(x=>x.value),email:form.elements.email.value}}
function moneyBand(d){const rev={"Under $10M":10000000,"$10M–$50M":50000000,"$50M–$250M":250000000,"$250M–$1B":1000000000,"$1B–$5B":5000000000,"Over $5B":10000000000}[d.revenue]||0;if(!rev)return null;const low=Math.round(rev*.002),high=Math.round(rev*.01);return{low,high};}
function fmt(n){return n>=1000000000?"$"+(n/1e9).toFixed(1)+"B":n>=1000000?"$"+(n/1e6).toFixed(1)+"M":n>=1000?"$"+Math.round(n/1000)+"K":"$"+n}
function render(d){const ind=INDUSTRIES[d.industry]||INDUSTRIES.Other, selected=d.processes.length?d.processes:ind.processes.slice(0,6), pains=d.pains.length?d.pains:ind.pains.slice(0,4);const score=Math.min(100,Math.round((selected.length/Math.max(ind.processes.length,1))*55+pains.length*5+(d.custom!=="Low"?10:0)+(d.integration!=="Low"?10:0)+(d.migration==="Transformational"?10:0)));tScore.textContent=score;tResultSub.textContent=d.industry+" · "+d.businessModel+" · "+d.current+" · "+d.scale;tInterpretation.textContent=score>=75?"A broad transformation case is visible — discovery should focus on target operating model, value and market fit.":score>=50?"There is enough signal for structured market discovery, but important requirements still need validation.":"Start with process and pain-point discovery before narrowing the technology market.";tSummary.textContent="AutomationScan has adapted this assessment to "+d.industry+". It considers "+selected.length+" selected process areas and "+pains.length+" stated pain points, then maps them to candidate technology ecosystems and value questions.";
tContext.innerHTML=[["Industry",d.industry],["Business model",d.businessModel],["Current platform",d.current],["Scale",d.scale],["Revenue",d.revenue],["Employees",d.employees],["Customisation",d.custom],["Integration",d.integration],["Horizon",d.horizon]].map(x=>"<div class='signal-row'><span>"+esc(x[0])+"</span><b>"+esc(x[1])+"</b></div>").join("");tContextLabel.textContent="your inputs";tCapCount.textContent=selected.length+" process areas";tCaps.innerHTML=selected.map(x=>"<span>"+esc(x)+"</span>").join("");
const opp=pains.slice(0,6).map((p,i)=>"<article class='candidate-card'><div><b>"+esc(p)+"</b><span>"+(i<2?"HIGH PRIORITY":"DISCOVERY")+"</span></div><strong>"+(i<2?"1":"2")+"<small>/ priority</small></strong><p>Investigate the process baseline, root cause, measurable business impact and whether the target capability should be native, specialised or automated.</p></article>");tOpportunities.innerHTML=opp.join("");
const candidates=Object.entries(platforms).map(([name,p])=>{const hit=selected.filter(x=>p.caps.includes(x)).length;const s=Math.round(hit/Math.max(selected.length,1)*100);return{name,s}}).sort((a,b)=>b.s-a.s);tCandidates.innerHTML=candidates.map(x=>"<article class='candidate-card'><div><b>"+x.name+"</b><span>"+(x.s>=75?"BROAD COVERAGE":x.s>=50?"PARTIAL COVERAGE":"VALIDATE SCOPE")+"</span></div><strong>"+x.s+"<small>/100</small></strong><p>Directional capability overlap only. Validate industry depth, localisation, integrations, implementation partners, licensing and target operating model.</p></article>").join("");
tMatrix.innerHTML="<thead><tr><th>Process / capability</th>"+Object.keys(platforms).map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+selected.map(cap=>"<tr><th>"+esc(cap)+"</th>"+Object.entries(platforms).map(([n,p])=>"<td><span class='fit-dot "+(p.caps.includes(cap)?"fit-3":"fit-1")+"'>"+(p.caps.includes(cap)?"Covered / validate":"Gap / specialist")+"</span></td>").join("")+"</tr>").join("")+"</tbody>";
const arch=[
["Core platform",d.current+" → target SaaS","Test whether ERP replacement is required or a phased coexistence model is safer.","ERP / finance / supply chain"],
["Industry layer",d.industry+" applications","Separate industry-specific capability from generic ERP capability.","Retail / manufacturing / healthcare etc."],
["Experience","Commerce / CRM / channels","Identify customer-facing capabilities that should not be forced into core ERP.","Commerce · POS · CRM"],
["Data & AI","Analytics / AI / automation","Define the data foundation and high-value AI use cases after process baselines exist.","Data · BI · AI"],
["Integration","API / events / middleware","Map system-of-record dependencies before deciding what moves.","Integration · APIs · events"]
];
tArchitecture.innerHTML=arch.map(x=>"<article><span>"+esc(x[0])+"</span><b>"+esc(x[1])+"</b><p>"+esc(x[2])+"</p><i>"+esc(x[3])+"</i></article>").join("");
const band=moneyBand(d);tValue.innerHTML=(band?[["Opportunity band",fmt(band.low)+" – "+fmt(band.high)],["Value lens","0.2%–1.0% of stated annual turnover"],["Best next input","Baseline hours, cost-to-serve, inventory, leakage and transaction volumes"]]:[["Opportunity band","Add annual turnover for a directional range"],["Value lens","Automation, simplification, working capital and leakage"],["Best next input","Baseline cost, volumes, hours and measurable business outcomes"]]).map(x=>"<article><b>"+esc(x[0])+"</b><strong>"+esc(x[1])+"</strong></article>").join("");
const qs=["Which selected processes create the highest measurable cost, delay, risk or lost revenue?","Which requirements are genuinely industry-specific versus legacy customisation?","Which capabilities must be native to the core platform and which can come from specialist products?","Which integrations are system-of-record dependencies?","What data must migrate, what can be archived and what data quality remediation is needed?","What localisation, regulatory, tax and country requirements apply?","Which three processes should be demonstrated end-to-end in vendor proof-of-concept sessions?","What is the baseline for cost, effort, inventory, revenue leakage and cycle time before claiming value?"];tQuestions.innerHTML=qs.map(q=>"<li>"+esc(q)+"</li>").join("");tRoadmap.innerHTML=[["Days 1–30","Business & process baseline","Validate process map · quantify pain · catalogue customisation · identify value baselines"],["Days 31–60","Market & architecture discovery","Scripted demos · fit/gap · target architecture · specialist ecosystem · integration/data assessment"],["Days 61–90","Commercial decision readiness","POC · TCO inputs · partner assessment · migration waves · RFP requirements · risk register"]].map(x=>"<article><span>"+x[0]+"</span><b>"+x[1]+"</b><p>"+x[2]+"</p></article>").join("");transformResults.classList.remove("hidden");transformResults.scrollIntoView({behavior:"smooth"});try{sessionStorage.setItem("automationscan_transform",JSON.stringify(d))}catch(e){}}
form.onsubmit=e=>{e.preventDefault();if(!valid())return;render(read())};tPrint.onclick=()=>{document.body.classList.add("printing-transform");window.addEventListener("afterprint",()=>document.body.classList.remove("printing-transform"),{once:true});setTimeout(()=>window.print(),80)};show(0);