const platforms={
Oracle:{label:"Oracle",caps:{Finance:3,Procurement:3,"Supply Chain":3,Warehouse:3,Merchandising:3,Planning:3,Inventory:3,Commerce:3,CRM:1,Data:3,AI:3,Integration:3},reason:"Broad enterprise ERP plus a deep retail cloud portfolio; especially relevant where retail merchandising, planning and inventory are core."},
SAP:{label:"SAP",caps:{Finance:3,Procurement:3,"Supply Chain":3,Warehouse:3,Merchandising:2,Planning:3,Inventory:3,Commerce:2,CRM:2,Data:3,AI:3,Integration:3},reason:"Broad enterprise platform for finance and supply chain transformation, with retail capabilities that need to be mapped to the target operating model."},
Microsoft:{label:"Microsoft",caps:{Finance:3,Procurement:3,"Supply Chain":3,Warehouse:3,Merchandising:2,Planning:3,Inventory:3,Commerce:3,CRM:3,Data:3,AI:3,Integration:3},reason:"Strong fit to investigate where Finance, Supply Chain and Commerce intersect with the Microsoft ecosystem and AI/Copilot capabilities."},
Infor:{label:"Infor",caps:{Finance:3,Procurement:3,"Supply Chain":3,Warehouse:3,Merchandising:3,Planning:3,Inventory:3,Commerce:2,CRM:1,Data:2,AI:3,Integration:3},reason:"Industry-focused cloud path worth examining when the current Infor estate already aligns closely to the target business processes."},
NetSuite:{label:"NetSuite",caps:{Finance:3,Procurement:2,"Supply Chain":2,Warehouse:2,Merchandising:1,Planning:2,Inventory:3,Commerce:2,CRM:2,Data:2,AI:2,Integration:3},reason:"Cloud ERP candidate to investigate where scope, complexity and operating model fit; complex retail requirements may need specialist ecosystem products."},
IFS:{label:"IFS",caps:{Finance:3,Procurement:3,"Supply Chain":3,Warehouse:3,Merchandising:1,Planning:2,Inventory:3,Commerce:1,CRM:2,Data:2,AI:3,Integration:3},reason:"Relevant to investigate for complex operations, supply chain, asset/service and enterprise workflows; retail-specific scope needs validation."}
};
const capabilityLabels={Finance:"Finance & controls",Procurement:"Procurement", "Supply Chain":"Supply chain",Warehouse:"Warehouse / WMS",Merchandising:"Merchandising",Planning:"Demand / supply planning",Inventory:"Inventory optimisation",Commerce:"Commerce / POS / omnichannel",CRM:"CRM / customer",Data:"Data / analytics",AI:"AI / intelligent automation",Integration:"Integration / APIs"};
const f=document.getElementById("transformForm"),steps=[...document.querySelectorAll(".t-step")],next=document.getElementById("tNext"),back=document.getElementById("tBack"),generate=document.getElementById("tGenerate");let current=0;
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[m]))}
function show(i){current=i;steps.forEach((s,n)=>s.classList.toggle("active",n===i));document.getElementById("tProgress").textContent="Step "+(i+1)+" of "+steps.length;document.getElementById("tProgressBar").style.width=((i+1)/steps.length*100)+"%";back.hidden=i===0;next.hidden=i===steps.length-1;generate.hidden=i!==steps.length-1}
function valid(){for(const x of steps[current].querySelectorAll("[required]"))if(!x.checkValidity()){x.reportValidity();return false}return true}
next.onclick=()=>{if(valid())show(Math.min(current+1,steps.length-1))};back.onclick=()=>show(Math.max(current-1,0));
function read(){return{industry:f.elements.industry.value,current:f.elements.current.value,scale:f.elements.scale.value,trigger:f.elements.trigger.value,caps:[...f.querySelectorAll('input[name="cap"]:checked')].map(x=>x.value),custom:f.elements.custom.value,integration:f.elements.integration.value,migration:f.elements.migration.value,ecosystem:f.elements.ecosystem.value,concern:f.elements.concern.value,output:f.elements.output.value,email:f.elements.email.value}}
function scorePlatform(p,d){let s=0;d.caps.forEach(c=>s+=p.caps[c]||0);const max=d.caps.length*3||1;if(d.ecosystem==="Microsoft-heavy"&&p.label==="Microsoft")s+=3;if(d.ecosystem==="SAP-heavy"&&p.label==="SAP")s+=3;if(d.ecosystem==="Oracle-heavy"&&p.label==="Oracle")s+=3;if(d.current===p.label)s+=d.migration==="Conservative"?3:1;if(d.custom==="Very high"&&p.label===d.current)s-=2;return Math.round(Math.max(0,Math.min(100,s/(max*1.0)*100))}
function fitLabel(v){return v>=82?"Strong capability alignment":v>=68?"Worth detailed discovery":v>=52?"Selective fit — validate gaps":"Requires significant scope validation"}
function render(d){const entries=Object.values(platforms).map(p=>({...p,score:scorePlatform(p,d)})).sort((a,b)=>b.score-a.score);const score=Math.round(d.caps.reduce((s,c)=>s+Math.max(...Object.values(platforms).map(p=>p.caps[c]||0)),0)/(Math.max(1,d.caps.length)*3)*100);document.getElementById("tScore").textContent=score;document.getElementById("tResultSub").textContent=d.industry+" · current platform: "+d.current+" · target trigger: "+d.trigger;document.getElementById("tInterpretation").textContent=score>=80?"Your requirements are specific enough to support a structured market comparison.":"Your requirements need more discovery before a defensible shortlist can be made.";document.getElementById("tSummary").textContent="The result is a decision-support starting point. It identifies ecosystems whose documented capability areas overlap with your selected needs, then highlights the questions that still require workshops, demos and commercial validation.";document.getElementById("tCapCount").textContent=d.caps.length+" selected";document.getElementById("tCaps").innerHTML=d.caps.length?d.caps.map(c=>"<span>"+esc(capabilityLabels[c])+"</span>").join(""):"<span>Select capabilities to sharpen the analysis.</span>";
const signals=[["Current platform",d.current],["Customisation",d.custom],["Integration complexity",d.integration],["Migration appetite",d.migration],["Existing ecosystem",d.ecosystem]];document.getElementById("tSignals").innerHTML=signals.map(x=>"<div class="signal-row"><span>"+esc(x[0])+"</span><b>"+esc(x[1])+"</b></div>").join("");
document.getElementById("tCandidates").innerHTML=entries.map(p=>"<article class="candidate-card"><div><b>"+p.label+"</b><span>"+fitLabel(p.score)+"</span></div><strong>"+p.score+"<small>/100</small></strong><p>"+esc(p.reason)+"</p></article>").join("");
const tbody=document.querySelector("#tMatrix tbody");tbody.innerHTML=d.caps.map(c=>"<tr><th>"+esc(capabilityLabels[c])+"</th>"+Object.values(platforms).map(p=>"<td><span class="fit-dot fit-"+p.caps[c]+"">"+(p.caps[c]===3?"Core":p.caps[c]===2?"Consider":"Validate")+"</span></td>").join("")+"</tr>").join("");
const qs=["Which Infor customisations are genuinely business-critical, and which can be retired rather than reproduced?","Which integrations are system-of-record dependencies versus convenience interfaces?","Which retail capabilities must be native versus acceptable through an ecosystem product or specialist solution?","What historical data must move, what can be archived, and what data-quality remediation is required?","Which reports, controls and localisations are mandatory on day one?","What are the peak transaction volumes, store/warehouse patterns and country requirements?","What is the target operating model for merchandising, planning, finance and supply chain?","Which capabilities require a proof-of-concept before commercial selection?"];document.getElementById("tQuestions").innerHTML=qs.map(x=>"<li>"+x+"</li>").join("");
const phases=[["Days 1–30","Capability discovery","Process workshops · current-state application inventory · customisation and integration catalogue · data scope"],["Days 31–60","Market validation","Scripted demos · fit/gap workshops · architecture options · migration waves · security/localisation checks"],["Days 61–90","Selection readiness","Shortlist evidence · TCO inputs · implementation partner assessment · risk register · RFP/POC plan"]];document.getElementById("tRoadmap").innerHTML=phases.map(x=>"<article><span>"+x[0]+"</span><b>"+x[1]+"</b><p>"+x[2]+"</p></article>").join("");
document.getElementById("transformResults").classList.remove("hidden");document.getElementById("transformResults").scrollIntoView({behavior:"smooth"});try{sessionStorage.setItem("automationscan_transform",JSON.stringify(d))}catch(e){}}
f.addEventListener("submit",e=>{e.preventDefault();if(!valid())return;render(read())});document.getElementById("tPrint").addEventListener("click",()=>{document.body.classList.add("printing-transform");window.addEventListener("afterprint",()=>document.body.classList.remove("printing-transform"),{once:true});setTimeout(()=>window.print(),80)});show(0);